name: 'Install HLint to be used with hlint-run'
description: 'Cached download of hlint binary release to be used with hlint-run'
inputs:
  version:
    description: 'hlint version'
    required: false
    default: '3.5'
outputs:
  hlint-dir:
    description: 'Directory containing the hlint executable'
  hlint-bin:
    description: 'Location of the hlint executable'
  version:
    description: 'Version of the hlint tool (same as input, if provided)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-down-circle'
  color: blue
